from __future__ import annotations

import getpass
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_LOCAL = ROOT / ".env.local"


def load_env_pairs(path: Path) -> dict[str, str]:
    pairs: dict[str, str] = {}
    if not path.exists():
        return pairs
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        pairs[key.strip()] = value.strip()
    return pairs


def save_env_pairs(path: Path, pairs: dict[str, str]) -> None:
    lines = [
        "# Local secrets for scene_recognition_design",
        "# This file is auto-generated by scripts/configure_keys.py",
        "",
    ]
    for key in ("OPENAI_API_KEY", "ANTHROPIC_API_KEY"):
        value = pairs.get(key, "")
        if value:
            lines.append(f"{key}={value}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def cli_fallback() -> int:
    print("GUI unavailable; fallback to CLI prompt.")
    existing = load_env_pairs(ENV_LOCAL)

    openai_current = "(configured)" if existing.get("OPENAI_API_KEY") else "(empty)"
    anthropic_current = "(configured)" if existing.get("ANTHROPIC_API_KEY") else "(empty)"
    print(f"OPENAI_API_KEY {openai_current}")
    print(f"ANTHROPIC_API_KEY {anthropic_current}")

    openai = getpass.getpass("OPENAI_API_KEY (leave blank to keep existing): ").strip()
    anthropic = getpass.getpass("ANTHROPIC_API_KEY (leave blank to keep existing): ").strip()

    if openai:
        existing["OPENAI_API_KEY"] = openai
    if anthropic:
        existing["ANTHROPIC_API_KEY"] = anthropic

    save_env_pairs(ENV_LOCAL, existing)
    print(f"Saved to {ENV_LOCAL}")
    return 0


def gui_prompt() -> int:
    import tkinter as tk
    from tkinter import messagebox

    existing = load_env_pairs(ENV_LOCAL)

    root = tk.Tk()
    root.title("Configure API Keys")
    root.geometry("620x230")
    root.resizable(False, False)

    title = tk.Label(root, text="Scene Recognition API Key Setup", font=("Helvetica", 16, "bold"))
    title.pack(pady=(12, 8))

    frame = tk.Frame(root)
    frame.pack(fill="x", padx=16)

    tk.Label(frame, text="OPENAI_API_KEY", width=20, anchor="w").grid(row=0, column=0, pady=8, sticky="w")
    openai_var = tk.StringVar(value=existing.get("OPENAI_API_KEY", ""))
    openai_entry = tk.Entry(frame, textvariable=openai_var, width=62, show="*")
    openai_entry.grid(row=0, column=1, pady=8, sticky="w")

    tk.Label(frame, text="ANTHROPIC_API_KEY", width=20, anchor="w").grid(row=1, column=0, pady=8, sticky="w")
    anthropic_var = tk.StringVar(value=existing.get("ANTHROPIC_API_KEY", ""))
    anthropic_entry = tk.Entry(frame, textvariable=anthropic_var, width=62, show="*")
    anthropic_entry.grid(row=1, column=1, pady=8, sticky="w")

    hint = tk.Label(
        root,
        text="Keys are saved to .env.local (local only). You can fill one or both providers.",
        fg="#444444",
    )
    hint.pack(pady=(6, 0))

    btn_frame = tk.Frame(root)
    btn_frame.pack(pady=14)

    def on_save() -> None:
        pairs = load_env_pairs(ENV_LOCAL)
        if openai_var.get().strip():
            pairs["OPENAI_API_KEY"] = openai_var.get().strip()
        if anthropic_var.get().strip():
            pairs["ANTHROPIC_API_KEY"] = anthropic_var.get().strip()
        save_env_pairs(ENV_LOCAL, pairs)
        messagebox.showinfo("Saved", f"Saved API keys to\n{ENV_LOCAL}")
        root.destroy()

    def on_cancel() -> None:
        root.destroy()

    tk.Button(btn_frame, text="Save", width=14, command=on_save).grid(row=0, column=0, padx=6)
    tk.Button(btn_frame, text="Cancel", width=14, command=on_cancel).grid(row=0, column=1, padx=6)

    root.mainloop()
    return 0


def main() -> int:
    try:
        # Respect headless environments.
        if sys.platform != "win32" and not os.environ.get("DISPLAY") and sys.platform != "darwin":
            return cli_fallback()
        return gui_prompt()
    except Exception:
        return cli_fallback()


if __name__ == "__main__":
    raise SystemExit(main())
